[window]
padding = { x = 10, y = 10}
decorations = "Buttonless"
opacity = 0.95
blur = true
option_as_alt = "Both"

[font]
size = 14.0

[font.normal]
family = "MesloLGL Nerd Font"
style = "Regular"

[font.bold]
family = "MesloLGL Nerd Font"
style = "Bold"

[font.italic]
family = "MesloLGL Nerd Font"
style = "Italic"

[font.bold_italic]
family = "MesloLGL Nerd Font"
style = "Bold Italic"

[cursor]
style = { shape = "Block", blinking = "On" }

[colors.primary]
background = "#1a1b26"
foreground = "#c0caf5"

[colors.normal]
black = "#15161e"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#a9b1d6"

[colors.bright]
black = "#414868"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#c0caf5"

[scrolling]
history = 10000

[keyboard]
bindings = [
  { key = "W", mods = "Command", action = "None" },
  { key = "Return", mods = "Command", action = "ToggleFullscreen"}
]

