# ~/.config/starship.toml

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

right_format = """$cmd_duration $time"""

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vicmd_symbol = "[❮](bold green)"

[time]
disabled = false
format = "[$time]($style)"
style = "dimmed white"
time_format = "%H:%M:%S"

[cmd_duration]
min_time = 2_000
format = "[$duration]($style)"
style = "dimmed yellow"
show_milliseconds = false

[aws]
symbol = " "

[buf]
symbol = " "

[bun]
disabled = true
symbol = " "

[c]
symbol = " "

[cpp]
symbol = " "

[cmake]
symbol = " "

[conda]
symbol = " "

[crystal]
disabled = true
symbol = " "

[dart]
disabled = true
symbol = " "

[deno]
disabled = true
symbol = " "

[directory]
truncation_length = 3
truncate_to_repo = true
format = "[$path]($style)[$read_only]($read_only_style) "
style = "bold cyan"
read_only = " 󰌾"
read_only_style = "red"
truncation_symbol = "…/"
[docker_context]
symbol = " "

[elixir]
disabled = true
symbol = " "

[elm]
disabled = true
symbol = " "

[fennel]
disabled = true
symbol = " "

[fossil_branch]
symbol = " "

[gcloud]
disabled = true
symbol = " "

[git_branch]
symbol = " "

[git_commit]
tag_symbol = '  '

[golang]
symbol = " "

[gradle]
disabled = true
symbol = " "

[guix_shell]
symbol = " "

[haskell]
disabled = true
symbol = " "

[haxe]
disabled = true
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
disabled = true
symbol = " "

[julia]
disabled = true
symbol = " "

[kotlin]
disabled = true
symbol = " "

[lua]
disabled = true
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
disabled = true
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[ocaml]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "
[package]
symbol = "󰏗 "

[perl]
disabled = true
symbol = " "

[php]
disabled = true
symbol = " "

[pijul_channel]
symbol = " "

[pixi]
disabled = true
symbol = "󰏗 "

[python]
symbol = " "

[rlang]
disabled = true
symbol = "󰟔 "

[ruby]
disabled = true
symbol = " "

[rust]
symbol = "󱘗 "

[scala]
disabled = true
symbol = " "

[swift]
disabled = true
symbol = " "

[zig]
disabled = true
symbol = " "
